variables:
  DENO_VERSION: "v0.7.0"
  TS_VERSION: "3.4.5"

# TODO DRY up the jobs
# TODO Try to get eslint to run under Deno, like prettier
jobs:
  - job: "Linux"
    pool:
      vmImage: "Ubuntu-16.04"
    steps:
      - template: .azure-pipeline/templates/test-steps.yml

  - job: "Mac"
    pool:
      vmImage: "macOS-10.13"
    steps:
      - script: npm install -g functional-red-black-tree
      - template: .azure-pipeline/templates/test-steps.yml

  - job: "Windows"
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: .azure-pipeline/templates/test-steps.yml
        parameters:
          win: true
