variables:
  DENO_VERSION: 'v0.2.5'

jobs:

- job: 'Linux'
  pool:
    vmImage: 'Ubuntu-16.04'
  steps:
  - script: curl -L https://deno.land/x/install/install.py | python - $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: deno test.ts --allow-run --allow-net --allow-write

- job: 'Mac'
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: curl -L https://deno.land/x/install/install.py | python - $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]$(HOME)/.deno/bin/'
  - script: deno test.ts --allow-run --allow-net --allow-write

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  # The url will change to https://deno.land/x/install/install.py once its updated.
  - powershell: iwr https://raw.githubusercontent.com/srijanreddy98/deno_install/master/install.ps1 -Outfile 'install.ps1'; ./install.ps1 $(DENO_VERSION)
  - script: echo '##vso[task.prependpath]C:\Users\VssAdministrator\.deno\bin\'
  - script: 'C:\Users\VssAdministrator\.deno\bin\deno.exe test.ts --allow-run --allow-net --allow-write'
