variables:
  DENO_VERSION: "v0.7.0"
  TS_VERSION: "3.4.5"

# TODO Try to get eslint to run under Deno, like prettier
jobs:
  - job: "Linux"
    pool:
      vmImage: "Ubuntu-16.04"
    parameters:
      - exe_name: "deno"
    steps:
      - template: azure-template.yml

  - job: "Mac"
    pool:
      vmImage: "macOS-10.13"
    parameters:
      - exe_name: "deno"
    steps:
      - template: azure-template.yml

  - job: "Windows"
    pool:
      vmImage: "vs2017-win2016"
    parameters:
      - exe_name: "deno.exe"
      - windows: 'true'
    steps:
      - template: azure-template.yml
