name: deploy-compat
on:
  push:
    branches: [main]
jobs:
  deploy-compat:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Deploy to Deno Deploy
        uses: denoland/deployctl@v1
        id: deploy
        with:
          project: std-deploy-compat-test
          entrypoint: _tools/deploy.ts

      - name: Check deployment
        run: curl --fail ${{ steps.deploy.outputs.url }}
