name: workspace publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Deno
        uses: denoland/setup-deno@v1
        with:
          # TODO(iuioiua): Revert once workspaces functionality is fixed in canary
          # See: https://github.com/denoland/deno/issues/24422
          # deno-version: canary
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Test
        run: deno task test

      - name: Publish to JSR
        run: deno publish
